### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by macabeus** [gambiconf/cfp-api#3]
Para deixar open source:
- [x] Documentar como fazer o setup do projeto (e.g., geração do `client_secret.json` e criação da panilha)
- [ ] A URL precisa ser obtida por meio de uma variável de ambiente: https://github.com/gambiconf/gambiconf.github.io/blob/main/src/network/cfp.ts

Para o CFP estar pronto para a próxima edição
- [ ] Enviar e-mail de confirmação da submissão.
  - [ ] No e-mail ter um link com um token para poder editar/cancelar a submissão
